"""initial financial core

Revision ID: ad4c52240188
Revises: 
Create Date: 2026-06-22 10:58:38.030257
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ad4c52240188'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('inquilino', 'parqueo_mensual', name='tipocuentacobro', native_enum=False, length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_cobro_tipo'), 'cuentas_cobro', ['tipo'], unique=False)
    op.create_table('responsables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsables_nombre'), 'responsables', ['nombre'], unique=True)
    op.create_table('inquilinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('plan_actual', sa.Enum('A', 'V', name='planpago', native_enum=False), nullable=False),
    sa.Column('dia_pago_actual', sa.Integer(), nullable=False),
    sa.Column('cuota_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_carta_legacy', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cuota_actual >= 0', name='ck_inquilinos_cuota_no_negativa'),
    sa.CheckConstraint('dia_pago_actual BETWEEN 1 AND 31', name='ck_inquilinos_dia_pago'),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuentas_cobro.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquilinos_cuenta_cobro_id'), 'inquilinos', ['cuenta_cobro_id'], unique=True)
    op.create_index(op.f('ix_inquilinos_nombre'), 'inquilinos', ['nombre'], unique=False)
    op.create_index(op.f('ix_inquilinos_responsable_id'), 'inquilinos', ['responsable_id'], unique=False)
    op.create_table('obligaciones_mensuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('plan_aplicado', sa.Enum('A', 'V', name='planpago', native_enum=False), nullable=False),
    sa.Column('dia_pago_aplicado', sa.Integer(), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('anulada', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('dia_pago_aplicado BETWEEN 1 AND 31', name='ck_obligaciones_dia_pago'),
    sa.CheckConstraint('monto_cuota >= 0', name='ck_obligaciones_monto_no_negativo'),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuentas_cobro.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_cobro_id', 'periodo', name='uq_obligacion_cuenta_periodo')
    )
    op.create_index(op.f('ix_obligaciones_mensuales_cuenta_cobro_id'), 'obligaciones_mensuales', ['cuenta_cobro_id'], unique=False)
    op.create_index(op.f('ix_obligaciones_mensuales_fecha_limite'), 'obligaciones_mensuales', ['fecha_limite'], unique=False)
    op.create_index(op.f('ix_obligaciones_mensuales_periodo'), 'obligaciones_mensuales', ['periodo'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('anulado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto_total > 0', name='ck_pagos_monto_positivo'),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuentas_cobro.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_cuenta_cobro_id'), 'pagos', ['cuenta_cobro_id'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_table('aplicaciones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('obligacion_id', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto_aplicado > 0', name='ck_aplicaciones_monto_positivo'),
    sa.ForeignKeyConstraint(['obligacion_id'], ['obligaciones_mensuales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id', 'obligacion_id', name='uq_aplicacion_pago_obligacion')
    )
    op.create_index(op.f('ix_aplicaciones_pago_obligacion_id'), 'aplicaciones_pago', ['obligacion_id'], unique=False)
    op.create_index(op.f('ix_aplicaciones_pago_pago_id'), 'aplicaciones_pago', ['pago_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aplicaciones_pago_pago_id'), table_name='aplicaciones_pago')
    op.drop_index(op.f('ix_aplicaciones_pago_obligacion_id'), table_name='aplicaciones_pago')
    op.drop_table('aplicaciones_pago')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_cuenta_cobro_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_obligaciones_mensuales_periodo'), table_name='obligaciones_mensuales')
    op.drop_index(op.f('ix_obligaciones_mensuales_fecha_limite'), table_name='obligaciones_mensuales')
    op.drop_index(op.f('ix_obligaciones_mensuales_cuenta_cobro_id'), table_name='obligaciones_mensuales')
    op.drop_table('obligaciones_mensuales')
    op.drop_index(op.f('ix_inquilinos_responsable_id'), table_name='inquilinos')
    op.drop_index(op.f('ix_inquilinos_nombre'), table_name='inquilinos')
    op.drop_index(op.f('ix_inquilinos_cuenta_cobro_id'), table_name='inquilinos')
    op.drop_table('inquilinos')
    op.drop_index(op.f('ix_responsables_nombre'), table_name='responsables')
    op.drop_table('responsables')
    op.drop_index(op.f('ix_cuentas_cobro_tipo'), table_name='cuentas_cobro')
    op.drop_table('cuentas_cobro')
    # ### end Alembic commands ###

