"""add monthly parking

Revision ID: f471b32de79e
Revises: ad4c52240188
Create Date: 2026-06-22 14:15:34.291919
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f471b32de79e'
down_revision: str | None = 'ad4c52240188'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_parqueo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('carro', 'bus', 'camion', 'otro', name='tipovehiculo', native_enum=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_espacios_parqueo_codigo'), 'espacios_parqueo', ['codigo'], unique=True)
    op.create_index(op.f('ix_espacios_parqueo_tipo_vehiculo'), 'espacios_parqueo', ['tipo_vehiculo'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.Enum('carro', 'bus', 'camion', 'otro', name='tipovehiculo', native_enum=False, length=20), nullable=False),
    sa.Column('propietario', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_index(op.f('ix_vehiculos_propietario'), 'vehiculos', ['propietario'], unique=False)
    op.create_index(op.f('ix_vehiculos_tipo'), 'vehiculos', ['tipo'], unique=False)
    op.create_table('contratos_parqueo_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('espacio_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('cuota_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('plan_actual', sa.Enum('A', 'V', name='planpago', native_enum=False), nullable=False),
    sa.Column('dia_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cuota_mensual >= 0', name='ck_contratos_cuota_no_negativa'),
    sa.CheckConstraint('dia_pago BETWEEN 1 AND 31', name='ck_contratos_dia_pago'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='ck_contratos_fechas_validas'),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuentas_cobro.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios_parqueo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_parqueo_mensual_cuenta_cobro_id'), 'contratos_parqueo_mensual', ['cuenta_cobro_id'], unique=True)
    op.create_index(op.f('ix_contratos_parqueo_mensual_espacio_id'), 'contratos_parqueo_mensual', ['espacio_id'], unique=False)
    op.create_index(op.f('ix_contratos_parqueo_mensual_responsable_id'), 'contratos_parqueo_mensual', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_contratos_parqueo_mensual_vehiculo_id'), 'contratos_parqueo_mensual', ['vehiculo_id'], unique=False)
    op.create_index('uq_contratos_espacio_activo', 'contratos_parqueo_mensual', ['espacio_id'], unique=True, sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))
    op.create_index('uq_contratos_vehiculo_activo', 'contratos_parqueo_mensual', ['vehiculo_id'], unique=True, sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_contratos_vehiculo_activo', table_name='contratos_parqueo_mensual', sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))
    op.drop_index('uq_contratos_espacio_activo', table_name='contratos_parqueo_mensual', sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))
    op.drop_index(op.f('ix_contratos_parqueo_mensual_vehiculo_id'), table_name='contratos_parqueo_mensual')
    op.drop_index(op.f('ix_contratos_parqueo_mensual_responsable_id'), table_name='contratos_parqueo_mensual')
    op.drop_index(op.f('ix_contratos_parqueo_mensual_espacio_id'), table_name='contratos_parqueo_mensual')
    op.drop_index(op.f('ix_contratos_parqueo_mensual_cuenta_cobro_id'), table_name='contratos_parqueo_mensual')
    op.drop_table('contratos_parqueo_mensual')
    op.drop_index(op.f('ix_vehiculos_tipo'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_propietario'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_espacios_parqueo_tipo_vehiculo'), table_name='espacios_parqueo')
    op.drop_index(op.f('ix_espacios_parqueo_codigo'), table_name='espacios_parqueo')
    op.drop_table('espacios_parqueo')
    # ### end Alembic commands ###

