"""add temporary parking

Revision ID: f81b7d59386b
Revises: f471b32de79e
Create Date: 2026-06-22 14:32:29.169271
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f81b7d59386b'
down_revision: str | None = 'f471b32de79e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liberaciones_temporales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_mensual_id', sa.Integer(), nullable=False),
    sa.Column('disponible_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disponible_hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('disponible_hasta > disponible_desde', name='ck_liberaciones_horario'),
    sa.ForeignKeyConstraint(['contrato_mensual_id'], ['contratos_parqueo_mensual.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liberaciones_temporales_contrato_mensual_id'), 'liberaciones_temporales', ['contrato_mensual_id'], unique=False)
    op.create_index(op.f('ix_liberaciones_temporales_disponible_desde'), 'liberaciones_temporales', ['disponible_desde'], unique=False)
    op.create_index(op.f('ix_liberaciones_temporales_disponible_hasta'), 'liberaciones_temporales', ['disponible_hasta'], unique=False)
    op.create_table('ocupaciones_temporales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('espacio_id', sa.Integer(), nullable=False),
    sa.Column('liberacion_temporal_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_tarifa', sa.Enum('por_hora', 'diaria', 'acordada', name='tipotarifa', native_enum=False, length=20), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_cobrado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('anulado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fecha_hora_salida IS NULL OR fecha_hora_salida >= fecha_hora_entrada', name='ck_ocupaciones_horario'),
    sa.CheckConstraint('monto_cobrado IS NULL OR monto_cobrado >= 0', name='ck_ocupaciones_cobro_no_negativo'),
    sa.CheckConstraint('tarifa >= 0', name='ck_ocupaciones_tarifa_no_negativa'),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios_parqueo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['liberacion_temporal_id'], ['liberaciones_temporales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocupaciones_temporales_espacio_id'), 'ocupaciones_temporales', ['espacio_id'], unique=False)
    op.create_index(op.f('ix_ocupaciones_temporales_fecha_hora_entrada'), 'ocupaciones_temporales', ['fecha_hora_entrada'], unique=False)
    op.create_index(op.f('ix_ocupaciones_temporales_fecha_hora_salida'), 'ocupaciones_temporales', ['fecha_hora_salida'], unique=False)
    op.create_index(op.f('ix_ocupaciones_temporales_liberacion_temporal_id'), 'ocupaciones_temporales', ['liberacion_temporal_id'], unique=False)
    op.create_index(op.f('ix_ocupaciones_temporales_responsable_id'), 'ocupaciones_temporales', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_ocupaciones_temporales_vehiculo_id'), 'ocupaciones_temporales', ['vehiculo_id'], unique=False)
    op.create_index('uq_ocupaciones_espacio_abierto', 'ocupaciones_temporales', ['espacio_id'], unique=True, sqlite_where=sa.text('fecha_hora_salida IS NULL AND anulado = 0'), postgresql_where=sa.text('fecha_hora_salida IS NULL AND anulado = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ocupaciones_espacio_abierto', table_name='ocupaciones_temporales', sqlite_where=sa.text('fecha_hora_salida IS NULL AND anulado = 0'), postgresql_where=sa.text('fecha_hora_salida IS NULL AND anulado = false'))
    op.drop_index(op.f('ix_ocupaciones_temporales_vehiculo_id'), table_name='ocupaciones_temporales')
    op.drop_index(op.f('ix_ocupaciones_temporales_responsable_id'), table_name='ocupaciones_temporales')
    op.drop_index(op.f('ix_ocupaciones_temporales_liberacion_temporal_id'), table_name='ocupaciones_temporales')
    op.drop_index(op.f('ix_ocupaciones_temporales_fecha_hora_salida'), table_name='ocupaciones_temporales')
    op.drop_index(op.f('ix_ocupaciones_temporales_fecha_hora_entrada'), table_name='ocupaciones_temporales')
    op.drop_index(op.f('ix_ocupaciones_temporales_espacio_id'), table_name='ocupaciones_temporales')
    op.drop_table('ocupaciones_temporales')
    op.drop_index(op.f('ix_liberaciones_temporales_disponible_hasta'), table_name='liberaciones_temporales')
    op.drop_index(op.f('ix_liberaciones_temporales_disponible_desde'), table_name='liberaciones_temporales')
    op.drop_index(op.f('ix_liberaciones_temporales_contrato_mensual_id'), table_name='liberaciones_temporales')
    op.drop_table('liberaciones_temporales')
    # ### end Alembic commands ###

